[package]
name = "oxa_policy_registry"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true

[dev-dependencies]
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true
casm = true
